#!/bin/bash

set -eu -o pipefail

SCHEME="sparasitica"

# From https://stackoverflow.com/a/246128 by Dave Dopson
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

SCHEME_DIR="$( cd $DIR/.. && pwd; )"
BIN_DIR="$( cd $DIR/../../../bin && pwd; )"

${BIN_DIR}/pubmlst_mlst_download.py $SCHEME --scheme-id 1 ${DIR}/genes.txt $SCHEME_DIR

# For some reason the ST column is labelled DST
sed 's/^DST/ST/' $SCHEME_DIR/profiles.tsv > $SCHEME_DIR/profiles.tsv.fixed
mv $SCHEME_DIR/profiles.tsv.fixed $SCHEME_DIR/profiles.tsv
