#!/bin/bash

set -eu -o pipefail

URL="http://enterobase.warwick.ac.uk/schemes/Salmonella.Achtman7GeneMLST"

# From https://stackoverflow.com/a/246128 by Dave Dopson
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

SCHEME_DIR="$( cd $DIR/.. && pwd; )"
BIN_DIR="$( cd $DIR/../../../bin && pwd; )"

${BIN_DIR}/enterobase_cgmlst_download.py --profiles ${DIR}/genes.txt $URL $SCHEME_DIR
