#!/bin/bash

set -eu -o pipefail

# From https://stackoverflow.com/a/246128 by Dave Dopson
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

SCHEME_DIR="$( cd $DIR/.. && pwd; )"
BIN_DIR="$( cd $DIR/../../../bin && pwd; )"

$BIN_DIR/ng_star.py $DIR/genes.txt $SCHEME_DIR
