#!/bin/bash

set -eu -o pipefail

SCHEME="otsutsugamushi"

# From https://stackoverflow.com/a/246128 by Dave Dopson
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

SCHEME_DIR="$( cd $DIR/.. && pwd; )"
BIN_DIR="$( cd $DIR/../../../bin && pwd; )"

cat $DIR/genes.txt | while read gene; do
  curl --fail --silent "https://pubmlst.org/bigsdb?db=pubmlst_otsutsugamushi_seqdef&page=downloadAlleles&locus=${gene}" | $BIN_DIR/NormalizeAlleles.py - $SCHEME_DIR/${gene}.fa.gz
done

curl --fail --silent "https://pubmlst.org/bigsdb?db=pubmlst_otsutsugamushi_seqdef&page=downloadProfiles&scheme_id=1" > $SCHEME_DIR/profiles.tsv

echo "Downloaded $SCHEME to $SCHEME_DIR"
