#!/bin/bash

set -eu -o pipefail

SCHEME="pubmlst_klebsiella_seqdef"
CGST_SCHEME="18"

# From https://stackoverflow.com/a/246128 by Dave Dopson
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

BIN_DIR="$( cd $DIR/../../../bin && pwd )"

GENE_FILE=${DIR}/genes.txt
URL_PREFIX="https://bigsdb.pasteur.fr/api/db/${SCHEME}/loci"
SCHEME_URL_PREFIX="https://bigsdb.pasteur.fr/api/db/${SCHEME}/schemes/${CGST_SCHEME}"
SCHEME_DIR="$( cd $DIR/.. && pwd; )"

${BIN_DIR}/bigsdb_cgmlst_download.py $GENE_FILE $URL_PREFIX $SCHEME_DIR --profiles=True --scheme_url=$SCHEME_URL_PREFIX
