#!/bin/bash

set -eu -o pipefail

REPO="nickjcroucher/pneumo-cgmlst"
API="https://api.github.com/repos/${REPO}/releases/latest"
CLONE_URL="https://github.com/${REPO}.git"

# From https://stackoverflow.com/a/246128 by Dave Dopson
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

SCHEME_DIR="$( cd $DIR/.. && pwd; )"
BIN_DIR="$( cd $DIR/../../../bin && pwd; )"
SCHEME_NAME="$(basename $SCHEME_DIR)"

tag_name=$(curl --silent --fail $API | jq -r '.tag_name')
echo "Checking out $tag_name from $REPO" 1>&2
[[ -d $DIR/scheme ]] && ( cd $DIR/scheme && git fetch origin && git checkout $tag_name; ) || git clone -b $tag_name $CLONE_URL $DIR/scheme

while read gene; do
  ${BIN_DIR}/NormalizeAlleles.py $DIR/scheme/loci/${gene}.fasta $SCHEME_DIR/${gene}.fa.gz
  echo "Reformatted $gene for $SCHEME_NAME"
done < $DIR/genes.txt
