#!/bin/bash

set -eu -o pipefail

SCHEME="cgMLST_v2"

# From https://stackoverflow.com/a/246128 by Dave Dopson
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

SCHEME_DIR="$( cd $DIR/.. && pwd; )"
BIN_DIR="$( cd $DIR/../../../bin && pwd; )"

$BIN_DIR/enterobase_cgmlst_download.py https://enterobase.warwick.ac.uk/api/v2.0/senterica/${SCHEME} $SCHEME_DIR
