#!/bin/bash

set -eu -o pipefail

SCHEME="klebsiella"

# From https://stackoverflow.com/a/246128 by Dave Dopson
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

SCHEME_DIR="$( cd $DIR/.. && pwd; )"
BIN_DIR="$( cd $DIR/../../../bin && pwd; )"

${BIN_DIR}/pubmlst_mlst_download.py $SCHEME --scheme-id 1 --server pasteur ${DIR}/genes.txt $SCHEME_DIR
${BIN_DIR}/remove.py $SCHEME_DIR/phoE.fa.gz 486
